// <auto-generated />
using System;
using GdrEngineNet.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GdrEngineNet.Database.Migrations
{
    [DbContext(typeof(GdrDbContext))]
    [Migration("20190615143157_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("GdrEngineNet.Database.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<DateTime>("LastLogin");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CharacteristicsId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("Experience");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName");

                    b.Property<string>("MiddleName");

                    b.Property<int>("UserId");

                    b.Property<string>("UserId1");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicsId");

                    b.HasIndex("UserId1");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.CharacterClassRole", b =>
                {
                    b.Property<int>("CharacterId");

                    b.Property<int>("ClassRoleId");

                    b.HasKey("CharacterId", "ClassRoleId");

                    b.HasIndex("ClassRoleId");

                    b.ToTable("CharacterClassRoles");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.CharacterGuildRole", b =>
                {
                    b.Property<int>("CharacterId");

                    b.Property<int>("GuildRoleId");

                    b.HasKey("CharacterId", "GuildRoleId");

                    b.HasIndex("GuildRoleId");

                    b.ToTable("CharacterGuildRoles");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.CharacterItem", b =>
                {
                    b.Property<int>("CharacterId");

                    b.Property<int>("ItemId");

                    b.Property<int>("Quantity");

                    b.HasKey("CharacterId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("CharacterItems");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.CharacterRaceRole", b =>
                {
                    b.Property<int>("CharacterId");

                    b.Property<int>("RaceRoleId");

                    b.HasKey("CharacterId", "RaceRoleId");

                    b.HasIndex("RaceRoleId");

                    b.ToTable("CharacterRaceRoles");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.CharacteristicsSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Agility");

                    b.Property<int>("Health");

                    b.Property<int>("Intelligence");

                    b.Property<int>("Mana");

                    b.Property<int>("Strength");

                    b.Property<int>("Toughness");

                    b.Property<int>("Willpower");

                    b.HasKey("Id");

                    b.ToTable("CharacteristicsSets");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Availability");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.ClassRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClassId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("ClassRole");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.GameAction", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CharacterId");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("RoomId");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("RoomId");

                    b.ToTable("Actions");

                    b.HasDiscriminator<string>("Discriminator").HasValue("GameAction");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.Guild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Availability");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.GuildRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GuildId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("GuildRoles");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Item");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Agility");

                    b.Property<int>("Availability");

                    b.Property<int>("Health");

                    b.Property<int>("Intelligence");

                    b.Property<int>("Mana");

                    b.Property<string>("Name");

                    b.Property<int>("Strength");

                    b.Property<int>("Toughness");

                    b.Property<int>("Willpower");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Races");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.RaceRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("RaceId");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("RaceRoles");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.DiceAction", b =>
                {
                    b.HasBaseType("GdrEngineNet.Database.Models.GameAction");

                    b.Property<string>("Bonuses");

                    b.Property<string>("Characteristic");

                    b.Property<int>("CharacteristicValue");

                    b.Property<int>("Result");

                    b.Property<int>("RolledDice");

                    b.HasDiscriminator().HasValue("DiceAction");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.MasterAction", b =>
                {
                    b.HasBaseType("GdrEngineNet.Database.Models.GameAction");

                    b.Property<string>("Text");

                    b.HasDiscriminator().HasValue("MasterAction");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.ModeratorAction", b =>
                {
                    b.HasBaseType("GdrEngineNet.Database.Models.GameAction");

                    b.Property<string>("Text")
                        .HasColumnName("ModeratorAction_Text");

                    b.HasDiscriminator().HasValue("ModeratorAction");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.TextAction", b =>
                {
                    b.HasBaseType("GdrEngineNet.Database.Models.GameAction");

                    b.Property<string>("Tag");

                    b.Property<string>("Text")
                        .HasColumnName("TextAction_Text");

                    b.HasDiscriminator().HasValue("TextAction");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.ConsumableItem", b =>
                {
                    b.HasBaseType("GdrEngineNet.Database.Models.Item");

                    b.Property<int?>("BonusesId");

                    b.Property<int>("Duration");

                    b.HasIndex("BonusesId");

                    b.HasDiscriminator().HasValue("ConsumableItem");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.EquipableItem", b =>
                {
                    b.HasBaseType("GdrEngineNet.Database.Models.Item");

                    b.Property<int?>("BonusesId")
                        .HasColumnName("EquipableItem_BonusesId");

                    b.HasIndex("BonusesId");

                    b.HasDiscriminator().HasValue("EquipableItem");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.KeyItem", b =>
                {
                    b.HasBaseType("GdrEngineNet.Database.Models.Item");

                    b.HasDiscriminator().HasValue("KeyItem");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.Character", b =>
                {
                    b.HasOne("GdrEngineNet.Database.Models.CharacteristicsSet", "Characteristics")
                        .WithMany()
                        .HasForeignKey("CharacteristicsId");

                    b.HasOne("GdrEngineNet.Database.Models.ApplicationUser", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId1");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.CharacterClassRole", b =>
                {
                    b.HasOne("GdrEngineNet.Database.Models.Character", "Character")
                        .WithMany("CharacterClassRoles")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GdrEngineNet.Database.Models.ClassRole", "ClassRole")
                        .WithMany("CharacterClassRoles")
                        .HasForeignKey("ClassRoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.CharacterGuildRole", b =>
                {
                    b.HasOne("GdrEngineNet.Database.Models.Character", "Character")
                        .WithMany("CharacterGuildRoles")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GdrEngineNet.Database.Models.GuildRole", "GuildRole")
                        .WithMany("CharacterGuildRoles")
                        .HasForeignKey("GuildRoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.CharacterItem", b =>
                {
                    b.HasOne("GdrEngineNet.Database.Models.Character", "Character")
                        .WithMany("CharacterItems")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GdrEngineNet.Database.Models.Item", "Item")
                        .WithMany("CharacterItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.CharacterRaceRole", b =>
                {
                    b.HasOne("GdrEngineNet.Database.Models.Character", "Character")
                        .WithMany("CharacterRaceRoles")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GdrEngineNet.Database.Models.RaceRole", "RaceRole")
                        .WithMany("CharacterRaceRoles")
                        .HasForeignKey("RaceRoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.ClassRole", b =>
                {
                    b.HasOne("GdrEngineNet.Database.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.GameAction", b =>
                {
                    b.HasOne("GdrEngineNet.Database.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GdrEngineNet.Database.Models.Room", "Room")
                        .WithMany("Actions")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.GuildRole", b =>
                {
                    b.HasOne("GdrEngineNet.Database.Models.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.RaceRole", b =>
                {
                    b.HasOne("GdrEngineNet.Database.Models.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.ConsumableItem", b =>
                {
                    b.HasOne("GdrEngineNet.Database.Models.CharacteristicsSet", "Bonuses")
                        .WithMany()
                        .HasForeignKey("BonusesId");
                });

            modelBuilder.Entity("GdrEngineNet.Database.Models.EquipableItem", b =>
                {
                    b.HasOne("GdrEngineNet.Database.Models.CharacteristicsSet", "Bonuses")
                        .WithMany()
                        .HasForeignKey("BonusesId");
                });
#pragma warning restore 612, 618
        }
    }
}
